title: DigPres
email: n@nkrabben.com
description: >- 
  Courses on digital preservation and curation taught at Pratt Institute
  and NYU by Nick Krabbenhoeft. All materials are open educational resources
baseurl: "" 
url: "http://www.digpres.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nkrabben
github_username: nkrabben


remote_theme: pmarsceill/just-the-docs
search_enabled: true
search_tokenizer_separator: /[\s/]+/
heading_anchors: true

plugins:
  - jekyll-remote-theme
