title: DigPres
email: n@nkrabben.com
description: >- 
  Courses on digital preservation and curation taught at Pratt Institute
  and NYU by Nick Krabbenhoeft. All materials are open educational resources
baseurl: "" 
url: "http://www.digpres.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nkrabben
github_username: nkrabben


remote_theme: broccolini/swiss
theme_color: gray

plugins:
  - jekyll-remote-theme
